### ISSUE TITLE
Sprites Using Index Colour Mode Changing Colours On Scroll

### ISSUE THREAD

**Issue by ClaytonMT** [CarbsCode/CarbsAsepriteExtensions#7] opened 2024-02-21 19:59 UTC
Hi,

**Describe the bug**
When using the script with an asesprite file that is using Colour Mode: Indexed, it changes the colours of the layer it is applied to.

**To Reproduce**
Colour Mode Indexed file, apply script to a coloured layer - the resulting frames (and original) are recoloured.

**Expected behavior**
Colour stays the same, background is given scrolling animation

**Screenshots**
Before:
![image](https://github.com/CarbsCode/CarbsAsepriteExtensions/assets/160783631/16fa399a-6982-43c7-848e-ebc1f11eb45f)

After:
![image](https://github.com/CarbsCode/CarbsAsepriteExtensions/assets/160783631/f6502f17-70bd-4c08-9232-66b05c489cc7)

**System Information (please complete the following information):**
Win 10 Pro

**Additional context**
NA

Thanks!

**Comment by CarbsCode** [comment] 2024-02-21 21:29
This is def not intended behavior, thank you for submitting this issue!

Would you be able to let me know which version of the tool and of which Aseprite version you are currently using?

Also if possible would you be able to send this .ase file so I could dig deeper in to this?  Curious as to how the layers and/or colors are set up in your project! If not I will try and re-produce with the steps above to see if I can get it to happen!

Thank you!

**Comment by ClaytonMT** [comment] 2024-02-22 10:00
Hi,

Thanks for the swift reply!

Sure:

Auto-Scroll v1.1.4
Aseprite v1.3.2-x64

I had to zip the file to upload it as it does not allow .ase. 

[run_try.zip](https://github.com/CarbsCode/CarbsAsepriteExtensions/files/14370617/run_try.zip)

There were only 2 layers as this was meant to be a file where I test characters running. I removed the layer with the player character, and the issue persists. I uploaded the file with the background only (before script is applied).

Regards,
Clayton

**Comment by ClaytonMT** [comment] 2024-03-12 18:54
Hi,

Any luck on fixing this please?

Regards,
Clayton

**Comment by CarbsCode** [comment] 2024-04-04 03:01
This seems to be an index color mode issue. Everything works as intended when swaping to RGB color mode. Very strange! Also sorry for the delay on this @ClaytonMT !

As a temp fix flipping in to rgb color mode performing the scroll then flipping back in to index mode might work!

Digging deeper in to why index mode is messing with things though.

**Comment by CarbsCode** [comment] 2024-04-12 16:34
Great news! I was able to get this fixed on the update I currently have in the works.

Planning to work on a few other features this weekend and hope to try and push this out soon. I will close this issue once the update is public! Thanks again for reporting this @ClaytonMT !

**Closed as completed** 2024-04-17 19:11 UTC
Labels: bug, Extension: BG Autoscroll
